version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/checkpoint"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/libs/checkpoint-conformance"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"


  - package-ecosystem: "uv"
    directory: "/libs/checkpoint-postgres"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/checkpoint-sqlite"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/cli"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/langgraph"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/prebuilt"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/libs/sdk-py"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/libs/cli/js-examples"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/libs/cli/js-monorepo-example"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all-dependencies:
        patterns:
          - "*"
