blank_issues_enabled: false
version: 2.1
contact_links:
  - name: ðŸ¤” Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/langchain-ai/langgraph/discussions/categories/q-a
  - name: Feature Request
    url: https://github.com/langchain-ai/langgraph/discussions/categories/ideas
    about: Suggest a feature or an idea
  - name: Show and tell
    about: Show what you built with LangChain
    url: https://github.com/langchain-ai/langgraph/discussions/categories/show-and-tell
  - name: Slack
    url:  https://www.langchain.com/join-community
    about: General community discussions
