name: Run notebooks

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core-version:
          - ">=0.3.0.dev4,<0.4.0"
          - "development"
          - "latest"

    name: "test (langchain-core: ${{ matrix.core-version }})"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python + Poetry
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: 3.11
          poetry-version: 1.7.1
          cache-key: test-langgraph-notebooks

      - name: Install dependencies
        run: |
          poetry install --with docs
          if [[ "${{ matrix.core-version }}" != "latest" && "${{ matrix.core-version }}" != "development" ]]; then
            poetry run pip install "langchain-core${{ matrix.core-version }}"
          fi

      - name: Start services
        run: make start-services

      - name: Prepare notebooks
        if: ${{ matrix.core-version == 'development' }}
        run: poetry run python docs/_scripts/prepare_notebooks_for_ci.py

      - name: Run notebooks
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
        run: |
          for file in $(find docs/docs/how-tos -name "*.ipynb")
          do
            echo "Executing $file"
            PIP_PRE=1 jupyter execute "$file"
          done

      - name: Stop services
        run: make stop-services
